CREATE TABLE [dbo].[CAD_CLIENTE] (
    [ID_CLIENTE]             INT           IDENTITY (1, 1) NOT NULL,
    [NOME_CLIENTE]           VARCHAR (200) NOT NULL,
    [TIPO_CLIENTE]           CHAR (1)      NOT NULL,
    [FANTASIA_CLIENTE]       VARCHAR (200) NULL,
    [CPF_CNPJ_CLIENTE]       VARCHAR (18)  NOT NULL,
    [INSC_MUNICIPAL_CLIENTE] VARCHAR (15)  NULL,
    [INSC_ESTADUAL_CLIENTE]  VARCHAR (15)  NULL,
    [FONE_CLIENTE_1]         VARCHAR (15)  NOT NULL,
    [FONE_CLIENTE_2]         VARCHAR (15)  NULL,
    [EMAIL_CLIENTE]          VARCHAR (30)  NULL,
    [CEP_CLIENTE]            VARCHAR (9)   NOT NULL,
    [ENDERECO_CLIENTE]       VARCHAR (100) NOT NULL,
    [BAIRRO_CLIENTE]         VARCHAR (50)  NOT NULL,
    [CIDADE_CLIENTE]         VARCHAR (50)  NOT NULL,
    [UF]                     VARCHAR (2)   NOT NULL,
    [COMPLEMENTO_CLIENTE]    VARCHAR (20)  NULL,
    [DATA_INCLUSAO_CLIENTE]  DATETIME      NOT NULL,
    [DATA_ALTERACAO_CLIENTE] DATETIME      NULL,
    [NUMERO_CLIENTE]         VARCHAR (10)  NULL
);

